In [1]:
import numpy as np
from IPython.display import display

In [3]:
# 1
numpy_array = np.arange(18, 54)
display(numpy_array)

array([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53])

In [13]:
# 2
reshaped_array = numpy_array.reshape(6, 6)
display(reshaped_array)

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53]])

In [19]:
# 3
index = reshaped_array[3, 2]
display(index)

38

In [49]:
# 4 
# I didn't get the number: 59
display(38 + 17)

55

In [51]:
# 1
np.random.seed(42)

In [53]:
# 2
rand_array = np.random.randint(1, 101, (5, 5))
display(rand_array)

array([[ 52,  93,  15,  72,  61],
       [ 21,  83,  87,  75,  75],
       [ 88, 100,  24,   3,  22],
       [ 53,   2,  88,  30,  38],
       [  2,  64,  60,  21,  33]])

In [55]:
# 3 
print('max:', rand_array.max())

max: 100


In [57]:
# 4
max_value = rand_array.max()
result = (max_value / 2) + 7
display(result)

57.0

In [59]:
# 5
# I didn't get the number: 54